<a href="https://colab.research.google.com/github/SowmyaDontha88/Python/blob/main/Numpy%26series12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
a=np.array([(1,2,3,4),(55,6,7,8)])
a

array([[ 1,  2,  3,  4],
       [55,  6,  7,  8]])

In [4]:
print(a.size)

8


In [5]:
print(a.shape)

(2, 4)


In [6]:
print(a.reshape(4,2))

[[ 1  2]
 [ 3  4]
 [55  6]
 [ 7  8]]


In [8]:
a[1,1]

6

In [13]:
a1=np.array([1,2,3,4])


In [14]:
print(a1.shape)

(4,)


In [19]:
a1.min()

1

In [18]:
a1.max()

4

In [17]:
a1.sum()

10

In [20]:
a1.prod()

24

In [21]:
a.sum(axis=0)

array([56,  8, 10, 12])

In [22]:
a.sum(axis=1)

array([10, 76])

SERIES

In [25]:
import pandas as pd

In [23]:
s=['a','b','c','d']
type(s)

list

In [26]:
pd.Series(s)

0    a
1    b
2    c
3    d
dtype: object

In [28]:
snacks=['pizza','burger','sandwich']

In [29]:
days=['mon','tue','wed']

In [30]:
pd.Series(data=snacks,index=days)

mon       pizza
tue      burger
wed    sandwich
dtype: object

In [34]:
dict={'a':1,'b':2,'c':3}

In [35]:
pd.Series(dict)

a    1
b    2
c    3
dtype: int64